# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a28f439591e067a8750eee43b6fc385d9912da8ae22576f2b6dd4024dddaf36965bab43f3bec7134f68f36fb4a145aa297d054db1f95f56235599013549a4fe

test:
  secret_key_base: f8c8e959e4723f1445fdee8502e96af317bb0d090285f0ab70e0ed789605225fc1695b5e57ca49b7cb38eea8715ba31bf487216432ca2b26f653e494697d8452

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
